import ElementButton from "../ElementButton";
import { attribute } from "../../assets/attributes";

export function TransitionMetalsGroups() {
  return (
    <div className="flex gap-3 mt-10 p scroll-pl-6 snap-x">
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Escândio"
        elementName="Sc"
        elementNumber="21"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Titânio"
        elementName="Ti"
        elementNumber="22"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Vanádio"
        elementName="V"
        elementNumber="23"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Cromo"
        elementName="Cr"
        elementNumber="24"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Manganês"
        elementName="Mn"
        elementNumber="25"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Ferro"
        elementName="Fe"
        elementNumber="26"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Cobalto"
        elementName="Co"
        elementNumber="27"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Níquel"
        elementName="Ni"
        elementNumber="28"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Cobre"
        elementName="Cu"
        elementNumber="29"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Zinco"
        elementName="Zn"
        elementNumber="30"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Ítrio"
        elementName="Y"
        elementNumber="39"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Zircônio"
        elementName="Zr"
        elementNumber="40"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Nióbio"
        elementName="ZNb"
        elementNumber="41"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Molibdênio"
        elementName="Mo"
        elementNumber="42"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Tecnécio"
        elementName="Tc"
        elementNumber="43"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Rutênio"
        elementName="Ru"
        elementNumber="44"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Ródio"
        elementName="Rh"
        elementNumber="42"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Paládio"
        elementName="Pd"
        elementNumber="46"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Prata"
        elementName="Ag"
        elementNumber="47"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Cádmio"
        elementName="Cd"
        elementNumber="48"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Háfnio"
        elementName="Hf"
        elementNumber="72"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Tântalo"
        elementName="Ta"
        elementNumber="73"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Tungstênio"
        elementName="W"
        elementNumber="74"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Rênio"
        elementName="Re"
        elementNumber="75"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Ósmio"
        elementName="Os"
        elementNumber="76"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Irídio"
        elementName="Ir"
        elementNumber="77"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Platina"
        elementName="Pt"
        elementNumber="78"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Ouro"
        elementName="Au"
        elementNumber="79"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Mercúrio"
        elementName="Hg"
        elementNumber="80"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Rutherfórdio"
        elementName="Rf"
        elementNumber="104"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Dúbnio"
        elementName="Db"
        elementNumber="105"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Seabórgio"
        elementName="Sg"
        elementNumber="106"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Bóhrio"
        elementName="Bh"
        elementNumber="107"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Hássio"
        elementName="Hs"
        elementNumber="108"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Meitnério"
        elementName="Mt"
        elementNumber="109"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Darmstádio"
        elementName="Ds"
        elementNumber="110"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Roentgênio"
        elementName="Rg"
        elementNumber="111"
      />
      <ElementButton
        attributes={attribute[0].className}
        dialogTitle="Copernício"
        elementName="Cn"
        elementNumber="112"
      />
    </div>
  );
}
